export const metadata = {
  title: "Everything Cars!",
  description: "Generated by Everything Cars!",
};

export default function CarsLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}
